export const categoryColors: Record<string, string> = {
  foundational: '#3ecf8e',
  practical: '#f5a623',
  advanced: '#ef4444',
  spectacular: '#d946ef',
};

export const demoIcons: Record<string, string> = {
  'measure-height': '📐',
  'resize-relayout': '↔️',
  'shrink-wrap': '📦',
  'dom-vs-pretext': '⚡',
  'masonry-cards': '🧱',
  'chat-bubbles': '💬',
  'canvas-layout': '🎨',
  'i18n-stress': '🌍',
  'flow-around-obstacle': '🌊',
  'rich-text-lines': '✨',
  'editorial-engine': '📰',
  'dragon-chase': '🐉',
  'wave-distortion': '🌊',
  'text-breakout': '🎮',
  'gravity-letters': '🪨',
  'text-vortex': '🌀',
  'text-silhouette': '🖤',
  'multi-column': '📰',
  'text-waterfall': '💧',
  'text-hourglass': '⏳',
  'audio-reactive': '🎵',
  'text-terrain': '🗺️',
  'typographic-heatmap': '🌡️',
  'voronoi-text': '🔷',
  'text-rain': '🌧️',
  'text-collision': '💥',
  'text-earthquake': '🌋',
  'streaming-text': '⚡',
  'living-document': '🧠',
  'text-fluid': '🫧',
  'text-origami': '📄',
  'text-black-hole': '🕳️',
  'pdf-reflow-engine': '🗞️',
  'subtitle-composer': '🎬',
  'incremental-layout-profiler': '📊',
  'topology-morph': '🧬',
  'text-regatta': '⛵',
  'text-ocean-sph': '🌊',
};
